jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Change working directory
        run: cd ./angular-client
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
