name: Tests
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: cd angular-client && npm install
      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
