name: CI—Angular Client Unit Tests
on:
  pull_request:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: cd angular-client && npm install
      - name: Install ng
        run: npm install -g @angular/cli
      - name: Test
        run: cd angular-client && ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
